### ISSUE TITLE
Tiled XML Layer Ordering

### ISSUE THREAD

**Issue by Dannflower** [bitcraft/PyTMX#106]
I hope this isn't a stupid question as I'm very new to Python, but if I am understanding this block of code correctly it first loads tile layers, image layers, and, lastly, object groups in that order. Doesn't this mean that the order of different layer types have not had their order preserved relative to each other? I.e. If object group A is between tile layers B and C in the XML file, they would appear in the layers list [B, C, A]?

I have seen a similar approach in another non-Python TMX library and have been scratching my head as to whether or not I am missing something. Shouldn't the order of tile layers/object groups/image layers relative to each other be preserved?

Thanks in advance for any thoughts on this and for sharing such a nice project!

https://github.com/bitcraft/PyTMX/blob/f52503891272de2c9b29f47a22bec65c5014ce11/pytmx/pytmx.py#L390-L397

**Comment by bitcraft** [comment]
Not a stupid question, you are correct.  TBH, I've never really considered trying to preserve the order of layers from tiled.  In my experience, I've never had a problem with this approach, and in the...4 years (?) or so that I've maintained this nobody has really asked about it until now.

This approach is needed to follow the same convention Tiled uses to reference tiles.  If you don't follow this order, tiles won't be loaded in the correct order.  It would be easy enough to go through the layers again and resort the layers if needed.

**Comment by Dannflower** [comment]
That's fair. Thanks for taking the time to reply!
