### ISSUE TITLE
PyTMX incorrectly loading larger tiles 

### ISSUE THREAD

**Issue by Lucid003** [bitcraft/pytmx#127]
Tiled is set up as with my default tile size being 16x16. Some of my tiles, however, are bigger and these are the ones that seem to be messed up. My big tiles are being drawn upward in Tiled and downward in-game.

Here's my reddit post for the full text: https://www.reddit.com/r/pygame/comments/jaqjzm/pytmx_tile_misplacement_issue/g8slh2g/?context=3

Posting this here as per request. I've attached my TMX file.
[courthouse yard.zip](https://github.com/bitcraft/PyTMX/files/5412443/courthouse.yard.zip)

**Comment by bitcraft** [comment]
thanks for uploading this.  could i also get the TSX?  really sory, didn't find the info i needed from the TMX.

**Comment by Lucid003** [comment]
[courthouse yard tsx.zip](https://github.com/bitcraft/PyTMX/files/5419862/courthouse.yard.tsx.zip)
Here's the tsx file. If you need my art assets, I can provide those as well, but it'll be messy because of the directory structure.

**Comment by bitcraft** [comment]
hey sorry for the long time with no update.  i've found the reason why this happens and unfortunately there isn't an easy fix.  tile expects that each tile will be drawn (biltted...) from the `lower-left corner`....while pygame will draw from the `upper-right corner`.  this is a fundamental difference that affects tiles that are larger than the map's tile size.

in order to fix this you can:
1) break up larger tiles so they match the size of the map, or
2) inspect each tile when drawing and offset the y coordinate to compensate for a large tile

the pseudo code looks something like this:
```python
for x, y, gid in layer.tiles():
    image = map.get_image(gid)
    x = x * map.tilewidth
    y = y * map.tileheight + (map.tileheight - image.get_height())
    screen.blit(image, (x, y))
```
...thats not exact, but you should be able to fill in the details.  hope that helps.

**Comment by bitcraft** [comment]
im going to close this because this is an issue with the difference between tiled's rendering and pygame.  the psuedo-code above should work fine, ive tested somethign similar now and can correctly render maps that have large tiles.  thanks for uploading your files and opening the issue.  i'll document this somewhere so there is an obvious solution in the future.
