### ISSUE TITLE
do not get specific layer coordinates

### ISSUE THREAD

**Issue by king-anduin** [bitcraft/pytmx#156]
hi guys, 
I have a map with an island and around it is water.

```python
def getMapWater(self):
        mapWater = []
        for x, y, image in self.tmx.layernames['water'].tiles():
            rect = image.get_rect()
            rect.topleft = (x * self.tw, y * self.th)
            mapWater.append(rect)
        return mapWater
```

I wanna get the coordinates for checking collision and when I only `print(x, y)` within the for loop,  I always get back all coordinates from all tiles. 
That's not how it's supposed to work when I use layernames, right?
Or is there any other function which does it?
thanks xD

**Comment by bitcraft** [comment]
there are not "guys" here...just be, one person.  if you want to post code, you need to surround it with "triple ticks" like this
![image](https://user-images.githubusercontent.com/556711/143167177-d58b3e97-50d3-4e8a-983f-1d5fcb48fbd5.png)
i don't see anything wrong with the code you posted.  it looks like its doing exactly what you want....giving you all the tiles that are in the "water" layer?  does the layer have a tile in all the available cells (x, y coordinates)?  feel free to zip the map or send it.  but as-is, i don't see a problem with the code itself.

**Comment by king-anduin** [comment]
sorry for the wrong code declaration and didn't now you're alone. Lovely software btw. it really makes my life easier xD.

[Archive.zip](https://github.com/bitcraft/pytmx/files/7593282/Archive.zip)

It's just a simple map and it gives me back all tiles from 0,9 till 9, 9

**Comment by bitcraft** [comment]
looking at the data...
```
 <layer id="1" name="water" width="10" height="10">
  <data encoding="csv">
41,41,41,41,41,41,41,41,41,41,
41,44,639,639,639,639,639,639,44,41,
41,639,639,559,559,559,559,639,639,41,
41,639,639,639,559,559,559,639,639,41,
41,639,639,639,639,639,559,639,639,41,
41,639,639,639,639,639,639,639,639,41,
41,639,639,639,639,639,639,639,639,41,
41,44,639,639,639,639,639,639,44,41,
41,44,44,639,639,639,639,44,44,41,
41,41,41,41,41,41,41,41,41,41
</data>
```
there are tiles in the water layer for every position.  so you will get an image and rect for every tile on the map, since the entire layer is filled with water tiles.  if you are doing collisions, there are a lot of ways to do it.
1) use this method, but you cannot have all the positions filled.  since there is a tile in each position, you will get a wall in each position.  remove tiles and try again.
2) create a new layer and draw box shapes for walls.  then load the shapes as rects:
```python
for obj in self.tmx.layernames['walls']:
    self.walls.append(pygame.Rect(obj.x, obj.y, obj.width, obj.height))
```
3) edit the tile properties you want to use as walls in tiled.  set the property on it to something like name: "wall", "True
```python
for obj in self.tmx.objects:
   if obj.wall:
      self.walls.append(pygame.Rect(obj.x, obj.y, obj.width, obj.height))
```
![image](https://user-images.githubusercontent.com/556711/143261044-17a1dda5-8876-48b1-a140-1c62ce6dca14.png)

**Comment by king-anduin** [comment]
thanks a lot for the explanation and pictures. Sorry for the inconvenience. Wish you a wonderful day.
