### ISSUE TITLE
pytmx.TiledMap.world_to_tile_pos()

### ISSUE THREAD

**Issue by novialriptide** [bitcraft/pytmx#168]
So let's say you want to get a tile's position on a TiledMap, but you only have the world position (let's say 40, 12). This function would return (2, 0) if the tile's width and height are 16.

Here's an image as example
![image](https://user-images.githubusercontent.com/35881688/169855334-a3332082-d82b-4929-ac69-a717bf81bc62.png)

EDIT: I realized the image isn't position-accurate, but hopefully you get what I mean.

**Comment by JRaunak** [comment]
This issue can be expanded with the support of Isometric Transformation

**Comment by bitcraft** [comment]
just adding my comment from the discord 
> Yeah I like the idea.  I’m hung up on the word “world” though.  Because that is kinda up to the game to determine the unit for the world.  And it’s often some fraction of a pixel.   I often refer to the units as either “map” coordinates or “pixel” coordinates.  But either way, I think it would be useful to have.

**Comment by JRaunak** [comment]
I guess the (pygame window pixel  ->  TiledMap Indices) could be the general implementation, on which users can apply modifications like offsetting (1, 1) of TiledMap to some arbritrary (x, y) coordinates instead of (0, 0).
You can define Transformation matrix for the axes to support isometric rendering and movement transformation

**Comment by novialriptide** [comment]
There's actually one problem with this. What if the map is scaled irregularly? The current example would only work if the world map is 1x scaled, but it wouldn't work if it was 1.2x or 45x scaled. Should we put in a kwarg value so that it would fix this?

**Comment by bitcraft** [comment]
> What if the map is scaled irregularly
i kinda wanted to avoid the word "world" for this reason.  i think that a conversion from *pixels* to tile position is probably safe and flexible enough to use.  i don't think the map loader should be aware of, or directly involved with, the conversion of world coordinates because it would be so different between games.  i guess if the interface is simple enough, it would be ok, but it feels redundant.

**Comment by novialriptide** [comment]
`pixels_to_tile_pos()` sounds good then.
