### ISSUE TITLE
Tiled 0.11.0 support

### ISSUE THREAD

**Issue by Rawng** [bitcraft/PyTMX#52]
It seems that pytmx does not like the "id" attribute that all objects now receive. In particular, it seems to trigger contains_invalid_property_name in pytmx.py.

**Comment by Rawng** [comment]
Issue was caused by having a object property with the name "id" conflicting with the object attribute 'id'.

**Comment by bitcraft** [comment]
Thanks for the report.  It seems the change creates a conflict where the tiled name conflicts with names created by the user.  By my design choices, I have a check that makes sure there are not duplicates in the tiles names and the user properties.  I have done this to make sure that maps cannot have ambiguous properties.  For example, with the checks, it is not possible to make a change to the data, but then later be confused, or forget if you changed the Tiled property, or the user property.

Because I feel this check makes the development of maps less confusing overall, I will not make an exception for this.  I'm sorry that the new change has created a problem.

**Comment by bitcraft** [comment]
https://github.com/bitcraft/PyTMX#reserved-names

New keyword argument to ignore duplicate name issues:
TiledMap(..., allow_duplicate_names=True)
load_pygame(..., allow_duplicate_names=True)

This will ignore the name checks and allow you to use names like 'id', 'name', and 'type'.  Just be aware that you need to double check the names you use from now on, if you use this option.
