### ISSUE TITLE
Loading and saving from file path too resctrictive

### ISSUE THREAD

**Issue by lillian-lemmer** [bitcraft/PyTMX#58]
For instance, what if I'm loading from a zip file? I'm not going to unzip he archive just for PyTMX. I want to pass PyTMX a file-like object, e.g., BytesIO, StringIO, file, to one of the loaders like `load_pygame()`. As per tile sources, you could make tile_source_directory an argument.

**Comment by lillian-lemmer** [comment]
Actually it seems like you should just update your documentation to say that the arg `blah` can be a file path or file-like-object, since [`xml.etree.ElementTree.parse` takes a file path OR file-like-object](https://docs.python.org/2/library/xml.etree.elementtree.html#xml.etree.ElementTree.parse).

**Comment by bitcraft** [comment]
Thanks for checking out pytmx.  There is a way I provided a long time ago to load from strings: https://github.com/bitcraft/pytmx#loading-from-xml-strings
Feel free to try it out.  I personally have not tested it for a long time, but I think it should work for you.  It relies on ElementTree.ElementTree.fromstring(...), so any limitations in that module will be present in pytmx.

Currently, tile graphic sources are handled the same way Tiled does, so that there are no surprises when loading tileset images from the filesystem.  The problem I see with the paths 'tile_source_folder' is that having an alternative path handling in pytmx would make the maps less accessible to edit in Tiled (because it expects paths to work in a certain way).  So while I do value your proposal for alternative path handling for the tileset images, I have to say no to this one; it would just complicate the interoperability between Tiled and pytmx.  If you have more supportive use cases, I would be happy to consider them.

Alternatively, you can create your own zip-file aware loader.  Perhaps if it is generic enough I can integrate it with pytmx in some future version.  If you are using pygame for loading, you can start with the pygame loader in pytmx.util_pygame, and modify the way images are loaded as pygame surfaces.  I suppose you would load the files from your zip bundle, then read them from pygame.image.fromstring (or whatever works for you!).
https://github.com/bitcraft/PyTMX/blob/master/pytmx/util_pygame.py#L64-L87
https://github.com/bitcraft/pytmx#custom-image-loading

When loading you would do something like this:
```python
    tiled_map = pytmx.TiledMap(..., image_loader=my_zip_pygame_loader)
```

Hope that helps, and good luck with Hypatia.

**Comment by lillian-lemmer** [comment]
Wow, thanks for the amazing reply! I'm working on my own implementation for reading "supported data" from a TMX file in Hypatia (see: `tiles.TileMap.from_tmx()`) on my `tmx-support` branch.
