### ISSUE TITLE
Odd (errors in?) translation of Terrain Types

### ISSUE THREAD

**Issue by Remusforte** [bitcraft/PyTMX#70]
I have recently started using Tiled and am trying to get a read of the tmx file into Python. Naturally, I turned to pytmx!
So admittedly I am a novice, but I occasionally see some "strange" (or just plain erroneous) translations of the tmx terrain type data as it comes into Python. 
Here I have a very simple example, and I am looking for what I am doing wrong... or is the loader making an error?
I have a test 5x5 map which has 5 terrain types defined in Tiled. This first attachment is a snip from Notepad showing the terrain type definitions and the data (stored in CSV) for the layer 1 of the map itself:
![test tmx file snip in notepad](https://cloud.githubusercontent.com/assets/16418812/11985437/dabb3b56-a992-11e5-99d6-c42f708f950c.JPG)
So, as you can see, there is a series of "3" terrains in the middle of the 5x5 map.
However, when I load that exact file into Python via pytmx, I get something a bit different. See this snip of the output for Layer 1:
![pytmx layer data for text tmx file](https://cloud.githubusercontent.com/assets/16418812/11985810/90d2b7ae-a996-11e5-9a33-679426279caa.JPG)
As you can see, there are indeed a series of different terrains in the middle of the map, but thet are coming back as "2", rather than "3"! So I am getting a mismatch.
Strangely, if I do this exact same test but with a couple of other terrains included in the map, they match perfectly! See this example:
![working example of pytmx load](https://cloud.githubusercontent.com/assets/16418812/11985822/ba2a90d6-a996-11e5-9d3e-799d3bb0c82b.JPG)
Either I am doing something wrong, or there is a bug in the loader that is incorrectly pulling in terraintypes, at least when there are only two of them in use.
Ideas?

**Comment by bitcraft** [comment]
Thanks for using pytmx. While I'm away from my desk now and cannot verify
this, I think I understand the issue. Pytmx by default only loads tiles
that are in use, so it skips tile numbers that are not used in the map.
This number is called the GID. This number isn't guaranteed to stay
constant in Tiled, so it's not a good idea to reference them.
You can add your own values to tiles via properties, or if you must include
all tiles, you can pass "load_all_tiles=True" to the constructor or loader.

**Comment by Remusforte** [comment]
Thx, bitcraft.
Good tip! I went back into Tiled and defined a custom property called "Type" which contains the name of the terrain type in each of the tiles defined. Using this, I was successfully able read the GID's, then grab their custom "Type" properties to extract the correct terrain name for my game. Great!

That said, I'm surprised when you say the GID numbers don't remain the same in Tiled. That has not been my experience so far... once the tiles are defined, I find that any map I build with that tileset retains the GID for the tiles as they were defined in Tiled. Look back at my example: In every map I create, the CSV data is always +1 from the "terrain names" as defined in Tiled and listed in the .tmx file. So when I load the file, it's a simple matter of -1 all those values, then look up the "Terrain name" from that list (or so I thought). It doesn't make any difference how many or which terrains I actually use in the map; the GID's are retained in the .tmx as far as I can tell.

IMHO, I'd refine pytmx to *retain* the original GID's as inputted and saved by Tiled, regardless of how many and which tiles are actually in use in the map. Why not? The data is all there, and not doing so seems to be a loss of (potentially) valuable information contained in the .tmx file. 

Meanwhile, your work-around of a custom property does have some really handy streamlining for me, so I am very happy. Thanks again!

**Comment by bitcraft** [comment]
The TMX specifications at one time said the GID values are not stable. They
would change if you adjust tilesets or tileset order. As far as I know that
is still the same, so GID values cannot be relied on. Pytmx was built for
pygame and large tilesets, so the compression that it uses is useful to
reduce memory consumption.

You can force pytmx to load all GID values, but still those may change so
it's not a good practice to rely on. Better to use custom properties since
they do not change.

Thanks for you input, but I won't be changing this, since there is a way to
override the behavior.

**Comment by Remusforte** [comment]
Gotcha; just thought I'd plant the thought. 
I still think there's room for something that retains info in the original .tmx file, yet keeps the compression you describe.
For example, you have a function in pytmx: t_map.get_tile_gid(x, y, layer) which conveniently accesses the GID for that location on the map. 
And the original .tmx file contains the "translation" of those GID's to actual terrain names (an inherent tile property in Tiled). 
So whether or not the GID values are stable, presumably the .tmx file, when written, will *always* have the GID's for all map locations along with the correct "translations" for GID->terrain name.
So...
Why not have a pytmx function: t_map.get_tile_terrain_name(x, y, layer) which grabs the "raw" GID stored in the .tmx file, then uses the "translation" (also stored in the .tmx file) to extract and return the terrain_name?
All that said, I'm still learning both Tiled and pytmx, so I'm probably not making ton of sense. Just a thought.

**Comment by bitcraft** [comment]
Any access to a dangerous, unstable function should be avoided.  GIDs are not stable, and change when the map changes in some ways (sometimes between versions of Tiled), so I will not encourage them to be used in that way.  They must be considered to be dynamic.  Don't assume that I haven't thought about it; I have.  It really is better to use custom properties, and that is why they exist.

Please use the 'load_all' flag if you insist on relying on GID values.  There is, optionally, an undocumented method that you can access to get the translation of raw GID to the ones that pytmx uses.  I however, cannot recommend that you rely on it, as it could change in the future.

https://github.com/bitcraft/PyTMX/blob/master/pytmx/pytmx.py#L710-L723

GID values are, and will always be an implementation detail that is subject to change.  Case in point, previous versions of Tiled changed all GID values to support rotating and flipped tiles.  It is certainly possible that GIDs will change again in the future to support new tile features.

I'm not sure that the Terrain name / GID mapping function you are proposing is useful to most people, since Terrains are more of a detail with editing in Tiled: they make it simple to define and draw regions of tiles with a brush, instead of placing corner tiles manually.  Some people will use them, some will not.

**Comment by Remusforte** [comment]
Gotcha, thanks. Didn't mean to imply you'd not thought it through and certainly didn't mean to insult in *any* way. Quite the opposite: I'm very thankful for your hard work! My apologies if it came across as anything else. View my comments/ideas as newbie (at best). And thanks again for all you did to make pytmx available to us. :-)
