### ISSUE TITLE
Get tile's properties from layer.tiles() is kind of cumbersome

### ISSUE THREAD

**Issue by touilleMan** [bitcraft/PyTMX#71]
Hi,

I've wrote a piece of code to load a map into my game. At a point I need to loop on my tiles to load them according to their position, image and properties.

The trick is `layer.tiles()` only provide the first two informations (position + image).

According to the documentation, I should use `get_tile_properties(x, y, layer)` and `get_tile_properties_by_guid(tile_gid)`, but:
- `get_tile_properties` needs a integer `layer` value which is the (and so is not directly available in the layer object)
- `layer.tiles()` doesn't provide the tile's gid, which means I can't use get_tile_properties_by_gid

For the moment, my solution is to keep a counter when iterating trough the layers to be able to use `get_tile_properties`

```python
for i, layer in enumerate(tmx.visible_layers):
    if isinstance(layer, pytmx.TiledTileLayer):
        # Iterate over the tiles in the layer
        for tile_x, tile_y, image in layer.tiles():
            # Get back tile's property
            properties = tmx.get_tile_properties(tile_x, tile_y, i)
            # Actually load the tiles into the game
            ...
```

However, it feel like a very clunky way to get this information...

Ideally, I would think `layer.tiles()` should return a `namedtuple` with fields `gid`, `x`, `y` , `image` and `properties`
Another solution (more backward compatible) would be to accept `get_tile_properties` to take either an integer or directly the layer object

Is there anything I've missed ?

**Comment by bitcraft** [comment]
Hey thanks for opening this issue.  I agree that for your use, using tiles() is not the right solution.  The method is made really only if you intend to draw using it.  I don't include the tile properties in that particular method because it involves a dictionary lookup for each tile.  Given that most tiles will not have properties set, and that tiles() is supposed to be for drawing, it didn't make sense to me to include the relatively slow dictionary lookup.  Namedtuples are not a bad suggestion, but I don't think they fit anywhere near a drawing operation, since they are slow to use (much slower than lists, dictionaries, etc).  Maybe in a new release...  Hope that helps!

Anyway, here is a suggestion for you.  Personally, I wouldn't render/draw a map using this, but it will work if you are just accessing the information, or don't need high fps.

```python
tmx_data = load_pygame(...)

for layer in tmx_data.visible_tile_layers:
    for x, y, gid in layer:
        tile_surface = tmx_data.get_tile_image_by_gid(gid)
        props = tmx_data.get_tile_properties_by_gid(gid)
        if props:
            ...
````

**Comment by touilleMan** [comment]
Thanks for the quick answer ! ^^

I understand better the reason of the `layer.tiles()` given it focus on performances, and thank you for the code snippet, it is the elegant way I was looking for !
