### ISSUE TITLE
Saving tmx data

### ISSUE THREAD

**Issue by ri0t** [bitcraft/PyTMX#77]
If #76 would be achievable, i think, storing back modified data is the next logical step (to have map states for savegames) - would that be possible? I'd help out if i can (as well as for #76)

**Comment by bitcraft** [comment]
I've thought about this often.  Pytmx does a lot of transformations to the data in order for it be be easy to use, so "going back" to the tmx data isn't straightforward.  Not to mention that pytmx can read gzip, zip, tmx, base64, etc.  I don't really want to add in all those formats for writing as well.

My advice is to use pytmx as it was designed...load the data, put into your own data structures, and save as you want it.  Going back to tmx doesn't really make sense to me.

I have used pickle before to save the map, but you need to set the map images to None first, because pickle cannot store pygame images.
